# Generated by Django 5.2.17 on 2026-09-19 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('election_id', models.CharField(max_length=100)),
                ('office_code', models.CharField(max_length=80)),
                ('jurisdiction_code', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('preparation', 'Preparação'), ('operation', 'Operação'), ('closing', 'Encerramento'), ('archived', 'Arquivada')], default='preparation', max_length=16)),
                ('timezone', models.CharField(default='America/Fortaleza', max_length=64)),
                ('is_demo', models.BooleanField(default=False)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=160, unique=True)),
                ('resource', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('scope', models.CharField(default='campaign', max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('archived', 'Arquivada')], db_index=True, default='active', max_length=16)),
                ('billing_profile_ref', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPhaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_phase', models.CharField(choices=[('preparation', 'Preparação'), ('operation', 'Operação'), ('closing', 'Encerramento'), ('archived', 'Arquivada')], max_length=16)),
                ('to_phase', models.CharField(choices=[('preparation', 'Preparação'), ('operation', 'Operação'), ('closing', 'Encerramento'), ('archived', 'Arquivada')], max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_events', to='campaigns.campaign')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='campaigns.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Convidado'), ('active', 'Ativo'), ('suspended', 'Suspenso'), ('revoked', 'Revogado')], db_index=True, default='invited', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='campaigns.campaign')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='campaigns.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='campaigns.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.tenant'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_role_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['campaign', 'status', 'expires_at'], name='campaigns_m_campaig_f1cac3_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'campaign'), name='uniq_membership_user_campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'phase', 'created_at'], name='campaigns_c_tenant__10d758_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_campaign_tenant_code'),
        ),
    ]
