# Generated by Django 5.2.17 on 2026-09-19 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('superseded', 'Substituído')], default='draft', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_budget_versions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.CharField(max_length=120)),
                ('funding_source', models.CharField(max_length=120)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('budget_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.budgetversion')),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('origin_type', models.CharField(max_length=80)),
                ('origin_id', models.UUIDField()),
                ('creditor_ref', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=255)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetida'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='draft', max_length=16)),
                ('documentation_status', models.CharField(choices=[('incomplete', 'Incompleta'), ('in_review', 'Em revisão'), ('verified', 'Conferida'), ('with_reservation', 'Com ressalva')], default='incomplete', max_length=24)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligation_version', models.PositiveBigIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Aprovada'), ('rejected', 'Rejeitada')], max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_decisions', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.obligation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('external_reference', models.CharField(max_length=180)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('paid_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('recorded', 'Registrado'), ('verified', 'Conferido'), ('reversed', 'Estornado')], default='recorded', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='finance.paymentrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.obligation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.paymentrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='budgetversion',
            constraint=models.UniqueConstraint(fields=('campaign', 'version_number'), name='uniq_budget_campaign_version'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget_version', 'cost_center', 'funding_source'), name='uniq_budget_line_dimension'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['campaign', 'approval_status', 'due_date'], name='finance_obl_campaig_3427eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.UniqueConstraint(fields=('campaign', 'origin_type', 'origin_id'), name='uniq_obligation_canonical_origin'),
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='obligation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(fields=('campaign', 'external_reference'), name='uniq_payment_campaign_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'obligation'), name='uniq_payment_obligation_allocation'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='allocation_amount_positive'),
        ),
    ]
