# Generated by Django 5.2.17 on 2026-09-19 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_seed_operations_permissions'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('cutoff_at', models.DateTimeField()),
                ('manifest_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('building', 'Em montagem'), ('reviewed', 'Conferido'), ('exported', 'Exportado'), ('delivered', 'Entregue'), ('rectified', 'Retificado')], default='building', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('funding_source', models.CharField(max_length=120)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('external_id', models.CharField(max_length=180)),
                ('occurred_at', models.DateTimeField()),
                ('amount_cents', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('original_line_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('unreconciled', 'Não conciliada'), ('partial', 'Parcial'), ('reconciled', 'Conciliada'), ('divergent', 'Divergente')], default='unreconciled', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.bankaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FilingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol_ref', models.CharField(max_length=180)),
                ('delivered_at', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filings', to='finance.accountingbatch')),
                ('evidence_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('origin_ref', models.CharField(max_length=180)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Revisado'), ('released', 'Liberado'), ('returned', 'Devolvido')], default='pending', max_length=16)),
                ('documentation_ref', models.CharField(blank=True, max_length=180)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InKindContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('origin_ref', models.CharField(max_length=180)),
                ('description', models.CharField(max_length=500)),
                ('estimated_amount_cents', models.PositiveBigIntegerField()),
                ('received_at', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='finance.bankentry')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='finance.paymentrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bankentry',
            constraint=models.UniqueConstraint(fields=('account', 'external_id'), name='uniq_bank_entry_external_id'),
        ),
        migrations.AddConstraint(
            model_name='bankentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='bank_entry_amount_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationlink',
            constraint=models.UniqueConstraint(fields=('entry', 'payment'), name='uniq_entry_payment_reconciliation'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationlink',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='reconciliation_amount_positive'),
        ),
    ]
