# Generated by Django 5.2.17 on 2026-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_accountingbatch_bankaccount_bankentry_filingrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingbatch',
            name='manifest_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
