"""Plain-language guidance shared by forms and contextual help. No personal data."""

FIELD_HELP = {
    "registration_name": "Nome informado pela pessoa que solicitou o cadastro. Não registre dados obtidos de listas sem autorização.",
    "name": "Use um nome que a equipe reconheça facilmente.",
    "title": "Dê um título curto e específico. Ex.: Organizar reunião de equipe.",
    "description": "Explique o que precisa ser feito. Evite repetir o título.",
    "project": "Agrupa tarefas do mesmo trabalho. Ex.: Organização do comitê.",
    "assignee": "Pessoa que vai executar e acompanhar este trabalho.",
    "responsible": "Pessoa da equipe responsável por acompanhar este registro.",
    "priority": "Ajuda a ordenar o trabalho. Não altera o prazo informado.",
    "due_at": "Data e horário esperados para a conclusão.",
    "due_date": "Data de vencimento. Não representa um pagamento realizado.",
    "completion_criteria": "Como a equipe saberá que terminou? Ex.: Material contado e conferido.",
    "requires_evidence": "Marque se a conclusão precisa de um documento de comprovação.",
    "evidence_document": "Documento já enviado e liberado para comprovar a execução.",
    "territory": "Área de atuação cadastrada pela equipe, como um bairro ou município.",
    "base": "Comitê ou ponto de encontro público usado pela equipe.",
    "base_type": "Identifica o uso do local. Não muda sua posição no mapa.",
    "public_address": "Endereço do local de operação. Não informe residências de eleitores.",
    "latitude": "Posição norte/sul. Opcional: sem coordenadas, o local fica na lista, mas não ganha um marcador no mapa.",
    "longitude": "Posição leste/oeste. Preencha junto com a latitude ou deixe ambas vazias.",
    "coordinator": "Pessoa que acompanha este território ou ponto de apoio.",
    "municipality": "Cidade informada no cadastro. Ex.: Fortaleza.",
    "opening_hours": "Horários em que a equipe pode usar este local.",
    "accessible": "Marque apenas se as condições de acessibilidade foram conferidas.",
    "owner": "Quem acompanha este cadastro. Por padrão, é você.",
    "purpose": "Motivo autorizado para guardar e usar estes dados. Não indica preferência ou intenção de voto.",
    "evidence_reference": "Referência do termo ou da solicitação. Não cole documentos pessoais neste campo.",
    "first_vote": "Informação declarada pela pessoa. Deixe como Não informado se não souber.",
    "voter_title": "Número opcional, informado pela própria pessoa. Não consultamos nem validamos o cadastro da Justiça Eleitoral.",
    "sku": "Código interno do material. Se ficar vazio em um novo cadastro, o sistema gera um código.",
    "unit": "Como o material é contado. Ex.: un, caixa ou kg. Se ficar vazio, usamos un (unidade). Não há conversão automática.",
    "item": "Material que entrou ou saiu. A quantidade usa a unidade do cadastro.",
    "warehouse": "Local onde o material está guardado. Com um único depósito, ele é selecionado automaticamente.",
    "quantity": "Informe uma quantidade maior que zero. A saída não pode ultrapassar o saldo disponível.",
    "kind": "Entrada aumenta o estoque; saída diminui. Devoluções também aumentam o saldo.",
    "reason": "Observação para ajudar a equipe a entender o registro. Não inclua dados pessoais sensíveis.",
    "supplier": "Empresa ou pessoa que fornece os materiais ou serviços.",
    "source_warehouse": "Depósito de onde o material vai sair.",
    "destination_warehouse": "Depósito que receberá o material após a conferência.",
    "expires_at": "Quando a reserva ou o acesso deixa de valer.",
    "amount_cents": "Valor em centavos, sem vírgula. Ex.: 15000 corresponde a R$ 150,00.",
    "estimated_amount_cents": "Estimativa em centavos. Ex.: 15000 corresponde a R$ 150,00.",
    "classification": "Define quais pessoas autorizadas podem consultar este documento.",
    "retention_policy": "Regra da organização que define por quanto tempo os dados são guardados.",
    "legal_basis_ref": "Referência definida pelo responsável pela privacidade. O sistema não escolhe uma base legal por você.",
    "allowed_fields": "Campos autorizados para esta finalidade, em formato JSON. Inclua first_vote e voter_title apenas quando autorizados.",
    "status": "Etapa atual do registro. Algumas mudanças exigem conferência de outra pessoa.",
    "username": "Nome usado para entrar no sistema. Cada pessoa deve ter seu próprio acesso.",
    "password": "Senha inicial da nova conta. Compartilhe somente com o destinatário, por um canal seguro.",
    "campaign": "Campanha à qual este acesso vai pertencer. Não libera acesso às demais campanhas ou organizações.",
    "starts_at": "Data e horário em que a atividade começa.",
    "ends_at": "Data e horário em que a atividade termina; deve ser depois do início.",
}

PAGE_HELP = {
    "projetos": "Agrupe tarefas de um mesmo trabalho. Ex.: Preparação do comitê. Primeiro crie o projeto, depois adicione as tarefas com responsáveis e prazos.",
    "tarefas": "Registre o que precisa ser feito, por quem e até quando. No detalhe da tarefa, acompanhe a etapa e as próximas ações disponíveis.",
    "territorios": "Organize áreas como municípios, bairros e comunidades. Você pode buscar pelo CEP e salvar sem desenhar um contorno. Endereços de comitês ficam em Pontos de apoio.",
    "comites": "Cadastre locais públicos usados pela equipe. As coordenadas são opcionais; sem elas o local fica salvo, mas ainda não aparece como marcador no mapa.",
    "cabos-eleitorais": "Organize integrantes, funções e áreas de trabalho. Este cadastro não cria um login: para liberar acesso ao sistema, use Equipe e acessos.",
    "acoes-de-rua": "Planeje uma atividade da equipe, com local, horário e pessoas necessárias. A aprovação e as escalas são acompanhadas no detalhe da ação.",
    "escalas-de-campo": "Vincule um integrante a uma ação e defina sua responsabilidade. Depois registre confirmação e presença; o sistema verifica conflitos de horário.",
    "agenda": "Organize encontros e eventos com data, local e responsável. Recursos reservados e aprovação são acompanhados no detalhe do evento.",
    "patrimonio": "Inventário de bens duráveis, como computadores e veículos. Para itens consumíveis, como papel, use Materiais e estoque.",
    "custodias": "Registre quem fica responsável por um bem e por qual período. O aceite e a devolução preservam o histórico de responsabilidade.",
    "logistica": "Planeje deslocamentos administrativos da equipe, com veículo, motorista, origem e destino. Não representa contratação ou pagamento automático.",
    "obrigacoes": "Registre despesas que precisam ser conferidas e aprovadas. Um lançamento não paga nem movimenta dinheiro; os pagamentos externos são registrados separadamente.",
    "pagamentos": "Registre pagamentos já realizados fora do sistema. Depois vincule-os às despesas correspondentes para acompanhar a quitação.",
    "contas": "Identifique as contas e fontes de recursos utilizadas. Este cadastro não conecta ao banco nem autoriza transações.",
    "extrato": "Compare lançamentos de extrato com pagamentos registrados para encontrar diferenças. Conciliar significa conferir essa correspondência.",
    "arrecadacao": "Registre receitas financeiras e suas referências documentais. O sistema organiza a conferência; não recebe ou transfere dinheiro.",
    "estimaveis": "Registre bens ou serviços recebidos sem entrada de dinheiro, com valor estimado e origem. Eles ficam separados das receitas em dinheiro.",
    "compras": "Use quando precisar solicitar uma compra antes da contratação. Informe o que é necessário, adicione os itens e encaminhe para aprovação.",
    "pedidos": "Acompanhe uma compra aprovada com fornecedor, valor e recebimentos. Use a conferência para registrar entregas parciais, sem duplicar estoque.",
    "depositos": "Locais onde os materiais ficam guardados. Use vários apenas se precisar controlar saldos separados; para uma operação simples, basta o estoque principal.",
    "reservas": "Separe uma quantidade para uso futuro. Ela continua no estoque físico, mas deixa de estar disponível para outras saídas até ser liberada ou consumida.",
    "transferencias": "Acompanhe materiais enviados de um depósito a outro. Eles ficam em trânsito até uma pessoa autorizada conferir a chegada.",
    "movimentos": "Histórico de entradas, saídas, devoluções e ajustes. Cada movimento explica uma alteração de saldo; não apague registros para corrigir diferenças.",
    "juridico": "Organize casos, documentos e responsáveis autorizados. A permissão geral do módulo não substitui as restrições de acesso de cada caso.",
    "prazos": "Acompanhe datas regulatórias com a fonte usada pela equipe. Os prazos devem ser revisados; o sistema não presume datas legais.",
    "documentos": "Envie arquivos privados e classifique o acesso. Eles só podem ser baixados após análise antivírus e com permissão correspondente.",
    "privacidade": "Acompanhe pedidos das pessoas sobre seus dados, como acesso, correção ou exclusão. Confira a identidade e registre o atendimento antes de encerrar.",
    "finalidades": "Configuração de privacidade: por que os dados são usados, quais campos podem ser coletados e por quanto tempo serão guardados. Deve ser revisada por uma pessoa responsável, não a cada cadastro diário.",
    "encerramento": "Confira as pendências e evidências antes de arquivar a campanha. Uma campanha arquivada fica somente para consulta.",
    "formularios": "Crie um formulário ligado a um uso autorizado dos dados. A versão e o aviso de privacidade precisam ser revisados antes de publicar um link.",
    "atendimentos": "Organize demandas recebidas, atribua responsáveis e acompanhe a resolução. O conteúdo pessoal é restrito a quem tem acesso atribuído.",
    "comunicacao": "Organize peças destinadas ao público geral, com autoria, direitos de uso e revisão. O registro de publicação não publica automaticamente em redes sociais.",
    "estudio": "Guarde referências de marca e versões de materiais, com arquivos e direitos de uso. Use a revisão para manter a equipe alinhada.",
    "propostas": "Organize propostas públicas e suas fontes. Registre a fundamentação e encaminhe para revisão antes de usar no material público.",
    "resultados": "Consulte dados oficiais agregados por geografia. Não é um cadastro individual nem uma ferramenta de inferência de voto de pessoas.",
    "escalas": "Planeje escalas e checklists administrativos do dia da eleição. O sistema não registra em quem alguém votou.",
    "ocorrencias": "Registre um relato para análise. Ele permanece identificado como não confirmado até a conferência; um registro não prova que o fato ocorreu.",
    "dashboard": "Visão geral da campanha. Os números e atalhos respeitam suas permissões. Abra um cartão para consultar os registros.",
    "map": "Escolha um estado e depois um município para navegar. Territórios são áreas de atuação; comitês são locais públicos. Só os locais com coordenadas aparecem como marcadores.",
    "team": "Crie um acesso individual e marque o que essa pessoa poderá usar. Opções desmarcadas não são concedidas. Revogar encerra o acesso a esta campanha, sem apagar o histórico.",
    "materials": "Cadastre o material uma vez. Depois registre entradas quando receber e saídas quando entregar. O saldo é calculado automaticamente. Fornecedores e recursos avançados ficam separados.",
    "reports": "Consulte os módulos permitidos para seu perfil e exporte seus registros, quando tiver autorização. A exportação fica registrada na auditoria.",
    "audit": "Histórico de quem fez cada ação e quando. Não é possível editar ou apagar os eventos pela interface.",
    "eleitores": "Cadastro voluntário da campanha, não um registro oficial de eleitores. Cadastro conferido significa que a solicitação foi revisada; não confirma voto. A finalidade vem das regras de privacidade da campanha.",
    "itens": "Cadastre cada material uma vez. Nome é obrigatório; código e unidade podem ser preenchidos automaticamente. Use Movimentar estoque para registrar entradas e saídas.",
    "fornecedores": "Guarde o nome de quem fornece materiais ou serviços. Cadastrar um fornecedor não cria uma compra nem uma dívida.",
}


def attach_guidance(form):
    """Keep native required/optional semantics and existing domain-specific help."""
    for name, field in form.fields.items():
        field.help_text = field.help_text or FIELD_HELP.get(name, "")
        if field.widget.is_hidden:
            continue
        if field.help_text:
            field.widget.attrs["aria-describedby"] = f"{form[name].auto_id}_helptext"
    return form
