"""Explicit UI allowlist. No model, field or permission is taken from user input."""
from dataclasses import dataclass

from apps.core.models import Document
from apps.finance.models import AccountingBatch, BankAccount, BankEntry, BudgetVersion, FinancialReceipt, InKindContribution, Obligation, PaymentRecord
from apps.forms.models import Form, Person, PrivacyRequest, ProcessingPurpose, ServiceRequest
from apps.operations.models import Project, PurchaseOrder, PurchaseRequest, StockItem, StockMovement, Supplier, Task, Warehouse
from .models import Asset, AssetBooking, BrandAsset, CampaignEvent, ClosureItem, EditorialContent, ElectionShift, LegalCase, LogisticsTrip, Occurrence, OfficialDataset, Proposal, RegulatoryDeadline, StockReservation
from .models import CampaignBase, CampaignProfile, ElectorRegistration, FieldActivity, FieldAssignment, FieldWorker, Territory


@dataclass(frozen=True)
class Module:
    key: str
    title: str
    subtitle: str
    group: str
    model: type
    fields: tuple
    columns: tuple
    read: str
    write: str
    review: str = ""
    editable: bool = True
    search: tuple = ("title",)


def module(key, title, subtitle, group, model, fields, columns, permission, *, read=None, review="", editable=True, search=("title",)):
    return Module(key, title, subtitle, group, model, tuple(fields.split()), tuple(columns.split()), read or permission, permission, review, editable, search)


MODULES = [
    module("candidatura", "Candidatura", "Identidade pública, cargo, partido e abrangência eleitoral.", "Campanha eleitoral", CampaignProfile, "candidate_name ballot_number party office election_date campaign_region motto", "candidate_name office campaign_region", "campaigns.manage.campaign", read="campaigns.read.campaign", search=("candidate_name",)),
    module("territorios", "Territórios", "Municípios, regiões de operação e coordenação territorial.", "Campanha eleitoral", Territory, "name municipality state ibge_code coordinator description", "name municipality state coordinator", "territories.manage.campaign", read="territories.read.campaign", search=("name", "municipality")),
    module("comites", "Comitês e pontos de apoio", "Locais públicos da campanha no mapa operacional.", "Campanha eleitoral", CampaignBase, "name territory base_type public_address latitude longitude coordinator opening_hours accessible public_location_confirmed", "name territory base_type status", "territories.manage.campaign", read="territories.read.campaign", search=("name", "public_address")),
    module("cabos-eleitorais", "Cabos eleitorais e voluntários", "Equipe de campanha, coordenação, capacitação e disponibilidade.", "Campanha eleitoral", FieldWorker, "name function territory base supervisor membership availability onboarding_reference", "name function territory training_status", "field.manage.campaign", search=("name",)),
    module("acoes-de-rua", "Ações de campanha", "Plantões, atos públicos, equipe de rua e apoio logístico.", "Campanha eleitoral", FieldActivity, "title description activity_type territory base responsible starts_at ends_at required_staff operational_checklist", "title activity_type territory starts_at status", "field.manage.campaign", review="field.approve.campaign"),
    module("escalas-de-campo", "Escalas de campo", "Pessoas escaladas, confirmação e presença por ação.", "Campanha eleitoral", FieldAssignment, "activity worker role_description", "worker activity role_description status", "field.manage.campaign", search=()),
    module("eleitores", "Cadastro de eleitores", "Contatos voluntários da campanha, com finalidade e acesso controlado. Não é o cadastro oficial da Justiça Eleitoral.", "Campanha eleitoral", ElectorRegistration, "purpose owner municipality evidence_reference", "person municipality source status created_at", "electors.create.assigned", read="electors.read.assigned", editable=False, search=()),
    module("orcamentos", "Orçamentos", "Versões e limites planejados por centro de custo e fonte.", "Financeiro", BudgetVersion, "version_number", "version_number status updated_at", "finance.create.campaign", read="finance.read.campaign", review="finance.approve.campaign", search=()),
    module("contabilidade", "Dossiês contábeis", "Fotografia dos registros. Exportar não equivale a protocolar.", "Financeiro", AccountingBatch, "cutoff_at", "cutoff_at status manifest_hash", "finance.create.campaign", read="finance.read.campaign", review="finance.approve.campaign", editable=False, search=()),
    module("pessoas", "Pessoas atribuídas", "Acesso limitado às pessoas vinculadas aos seus atendimentos.", "Relacionamento", Person, "", "id review_status created_at", "people.read.assigned", editable=False, search=()),
    module("projetos", "Projetos", "Objetivos claros, entregas acompanhadas.", "Operação", Project, "title description", "title status updated_at", "tasks.manage.campaign"),
    module("tarefas", "Tarefas", "Prioridades, responsáveis e dependências em um só lugar.", "Operação", Task, "project title description assignee priority due_at completion_criteria requires_evidence evidence_document", "title priority status due_at", "tasks.manage.campaign"),
    module("agenda", "Agenda e eventos", "Coordene eventos com acessibilidade e recursos reservados.", "Operação", CampaignEvent, "title description responsible starts_at ends_at location capacity accessibility_plan public_summary", "title starts_at location status", "events.manage.campaign", review="events.approve.campaign"),
    module("patrimonio", "Patrimônio", "Bens próprios, locados e cedidos, com rastreabilidade.", "Operação", Asset, "name inventory_code ownership description document_due", "name inventory_code ownership condition", "assets.manage.campaign", search=("name", "inventory_code")),
    module("custodias", "Reservas de patrimônio", "Períodos exclusivos e aceite de responsabilidade.", "Operação", AssetBooking, "asset event custodian starts_at ends_at", "asset custodian starts_at status", "assets.manage.campaign", search=()),
    module("logistica", "Logística", "Viagens administrativas, veículos e motoristas.", "Operação", LogisticsTrip, "title description responsible vehicle driver departure_at return_at origin destination", "title vehicle departure_at status", "logistics.manage.campaign", review="logistics.approve.campaign"),
    module("obrigacoes", "Obrigações", "Despesas com aprovação independente e valores em centavos.", "Financeiro", Obligation, "creditor_ref description amount_cents due_date", "description creditor_ref amount_cents approval_status", "finance.create.campaign", read="finance.read.campaign", review="finance.approve.campaign", search=("description", "creditor_ref")),
    module("pagamentos", "Pagamentos", "Registro de pagamentos externos. O sistema não movimenta dinheiro.", "Financeiro", PaymentRecord, "external_reference amount_cents paid_at", "external_reference amount_cents paid_at status", "finance.reconcile.campaign", read="finance.read.campaign", editable=False, search=("external_reference",)),
    module("contas", "Contas bancárias", "Contas e fontes de recurso, sem acesso ao banco.", "Financeiro", BankAccount, "name funding_source", "name funding_source currency active", "finance.create.campaign", read="finance.read.campaign", search=("name",)),
    module("extrato", "Conciliação", "Compare lançamentos externos e pagamentos registrados.", "Financeiro", BankEntry, "account external_id occurred_at amount_cents description", "external_id occurred_at amount_cents status", "finance.reconcile.campaign", read="finance.read.campaign", editable=False, search=("external_id", "description")),
    module("arrecadacao", "Arrecadação", "Receitas financeiras com revisão documental.", "Financeiro", FinancialReceipt, "origin_ref amount_cents received_at documentation_ref", "origin_ref amount_cents received_at status", "finance.create.campaign", read="finance.read.campaign", review="finance.approve.campaign", search=("origin_ref",)),
    module("estimaveis", "Contribuições estimáveis", "Bens e serviços separados do fluxo de caixa.", "Financeiro", InKindContribution, "origin_ref description estimated_amount_cents received_at", "description estimated_amount_cents received_at reviewed", "finance.create.campaign", read="finance.read.campaign", review="finance.approve.campaign", search=("description", "origin_ref")),
    module("fornecedores", "Fornecedores", "Cadastro administrativo de parceiros e prestadores.", "Suprimentos", Supplier, "name", "name status updated_at", "purchases.create.campaign", search=("name",)),
    module("compras", "Solicitações de compra", "Justificativa, itens e decisão antes da contratação.", "Suprimentos", PurchaseRequest, "justification destination", "destination status updated_at", "purchases.create.campaign", review="purchases.approve.campaign", search=("destination", "justification")),
    module("pedidos", "Pedidos de compra", "Pedido aprovado, obrigação única e recebimentos parciais.", "Suprimentos", PurchaseOrder, "purchase_request supplier amount_cents", "supplier amount_cents status updated_at", "purchases.create.campaign", review="purchases.approve.campaign", search=()),
    module("itens", "Itens de estoque", "Unidades explícitas, sem conversões automáticas.", "Suprimentos", StockItem, "name sku unit", "name sku unit updated_at", "stock.manage.campaign", search=("name", "sku")),
    module("depositos", "Depósitos", "Locais de armazenamento e saldos por item.", "Suprimentos", Warehouse, "name code", "name code updated_at", "stock.manage.campaign", search=("name", "code")),
    module("reservas", "Reservas de estoque", "Disponibilidade separada de saldo físico.", "Suprimentos", StockReservation, "item warehouse quantity purpose expires_at", "item quantity expires_at status", "stock.manage.campaign", editable=False, search=("purpose",)),
    module("movimentos", "Movimentos de estoque", "Histórico de entradas, saídas e devoluções.", "Suprimentos", StockMovement, "", "item warehouse signed_quantity kind", "stock.manage.campaign", editable=False, search=()),
    module("juridico", "Jurídico", "Casos restritos, referências e prazos revisados.", "Governança", LegalCase, "title description responsible due_at reference case_type source_ref restricted_document", "title case_type due_at status", "legal.manage.campaign", review="legal.approve.campaign"),
    module("prazos", "Calendário regulatório", "Fontes normativas e vigência. Sem prazos legais presumidos.", "Governança", RegulatoryDeadline, "title description responsible due_at source_url source_excerpt effective_from effective_until severity", "title due_at severity status", "rules.manage.campaign", review="rules.approve.campaign"),
    module("documentos", "Documentos", "Arquivos privados, hash de integridade e quarentena antivírus.", "Governança", Document, "display_name classification retention_policy", "display_name classification status updated_at", "documents.create.campaign", read="documents.read.campaign", editable=False, search=("display_name",)),
    module("privacidade", "Solicitações de privacidade", "Protocolo e acompanhamento dos direitos do titular.", "Governança", PrivacyRequest, "request_type due_at", "protocol request_type verification_status due_at", "privacy.handle.campaign", search=("protocol",)),
    module("encerramento", "Encerramento", "Checklist de evidências antes do arquivamento da campanha.", "Governança", ClosureItem, "title area responsible evidence_reference", "title area completed_at updated_at", "closure.manage.campaign"),
    module("atendimentos", "Atendimentos", "Triagem e resolução de demandas administrativas.", "Relacionamento", ServiceRequest, "category assignee due_at resolution_summary", "protocol category status due_at", "service.manage.campaign", search=("protocol", "category")),
    module("finalidades", "Finalidades de tratamento", "Campos permitidos, base de referência e retenção.", "Relacionamento", ProcessingPurpose, "code description legal_basis_ref allowed_fields retention_policy", "code status updated_at", "privacy.handle.campaign", search=("code", "description")),
    module("formularios", "Formulários", "Versões revisadas, avisos de privacidade e links públicos.", "Relacionamento", Form, "purpose title slug opens_at closes_at", "title status updated_at", "forms.create.campaign", review="forms.review.campaign"),
    module("comunicacao", "Comunicação", "Peças para o público geral, revisão e registro de publicação.", "Conteúdo", EditorialContent, "title description responsible due_at channel body rights_reference planned_at", "title channel planned_at status", "content.manage.campaign", review="content.approve.campaign"),
    module("estudio", "Estúdio e marca", "Versões, licenças e arquivos de produção.", "Conteúdo", BrandAsset, "title description responsible asset_type rights_reference version_label document", "title asset_type version_label status", "content.manage.campaign", review="content.approve.campaign"),
    module("propostas", "Propostas", "Fontes e fundamentação para propostas públicas.", "Conteúdo", Proposal, "title description responsible policy_area statement_type source_url methodology", "title policy_area statement_type status", "proposals.manage.campaign", review="proposals.approve.campaign"),
    module("resultados", "Resultados públicos", "Dados agregados de fontes oficiais, sem perfis individuais.", "Inteligência administrativa", OfficialDataset, "title source_url reference_year coverage methodology", "title reference_year coverage row_count", "results.manage.campaign", editable=False),
    module("escalas", "Dia da eleição", "Escalas e checklists administrativos, sem registro de voto.", "Inteligência administrativa", ElectionShift, "title description responsible location starts_at ends_at checklist", "title location starts_at status", "election.manage.campaign", review="election.approve.campaign"),
    module("ocorrencias", "Ocorrências", "Relatos identificados como não confirmados até revisão.", "Inteligência administrativa", Occurrence, "title description responsible occurred_at location legal_case", "title location verification status", "legal.manage.campaign", review="legal.approve.campaign"),
]
REGISTRY = {item.key: item for item in MODULES}

LABELS = {
    "title": "Título", "name": "Nome", "description": "Descrição", "status": "Situação", "updated_at": "Atualizado", "created_at": "Criado em", "project": "Projeto", "assignee": "Responsável", "responsible": "Responsável", "priority": "Prioridade", "due_at": "Prazo", "due_date": "Vencimento", "completion_criteria": "Critérios de conclusão", "requires_evidence": "Exigir evidência", "evidence_document": "Documento de evidência", "creditor_ref": "Credor / referência", "amount_cents": "Valor (centavos)", "estimated_amount_cents": "Valor estimado (centavos)", "approval_status": "Aprovação", "external_reference": "Referência externa", "paid_at": "Pago em", "funding_source": "Fonte do recurso", "currency": "Moeda", "active": "Ativa", "account": "Conta", "external_id": "Identificador no extrato", "occurred_at": "Ocorrido em", "origin_ref": "Referência da origem", "received_at": "Recebido em", "documentation_ref": "Referência documental", "reviewed": "Revisado", "justification": "Justificativa", "destination": "Destino", "purchase_request": "Solicitação de compra", "supplier": "Fornecedor", "sku": "SKU", "unit": "Unidade", "code": "Código", "item": "Item", "warehouse": "Depósito", "quantity": "Quantidade", "signed_quantity": "Quantidade movimentada", "kind": "Tipo", "purpose": "Finalidade", "expires_at": "Expira em", "display_name": "Nome do documento", "classification": "Classificação", "retention_policy": "Política de retenção", "protocol": "Protocolo", "request_type": "Tipo de solicitação", "verification_status": "Verificação", "completed_at": "Concluído em", "category": "Categoria", "resolution_summary": "Resumo da resolução", "legal_basis_ref": "Referência da base legal", "allowed_fields": "Campos permitidos (JSON)", "slug": "Identificador", "opens_at": "Abre em", "closes_at": "Encerra em", "row_count": "Linhas", "starts_at": "Início", "ends_at": "Fim", "location": "Local", "condition": "Condição", "asset": "Bem", "custodian": "Custodiante", "vehicle": "Veículo", "driver": "Motorista", "departure_at": "Partida", "restricted_document": "Documento restrito", "document": "Documento", "legal_case": "Caso jurídico", "severity": "Efeito", "verification": "Verificação", "row_version": "Versão", "return_condition": "Condição na devolução"
}
LABELS.update({"candidate_name": "Candidatura", "ballot_number": "Número", "party": "Partido / federação", "office": "Cargo", "election_date": "Data da eleição", "campaign_region": "Abrangência", "motto": "Identificação pública", "municipality": "Município", "state": "UF", "ibge_code": "Código IBGE", "coordinator": "Coordenação", "territory": "Território", "base_type": "Tipo de ponto", "public_address": "Endereço público", "latitude": "Latitude", "longitude": "Longitude", "opening_hours": "Horários", "accessible": "Acessibilidade conferida", "public_location_confirmed": "Local público confirmado", "function": "Função na campanha", "base": "Comitê / ponto de encontro", "supervisor": "Supervisão", "membership": "Vínculo de acesso", "availability": "Disponibilidade", "onboarding_reference": "Referência do termo", "training_status": "Capacitação", "activity_type": "Tipo de ação", "required_staff": "Equipe necessária", "operational_checklist": "Checklist operacional", "activity": "Ação de campanha", "worker": "Integrante", "role_description": "Responsabilidade", "owner": "Responsável pelo cadastro", "person": "Nome cadastrado", "source": "Origem", "evidence_reference": "Referência da manifestação", "version_number": "Versão", "cutoff_at": "Data de corte", "manifest_hash": "Hash do manifesto", "review_status": "Revisão", "id": "Identificador"})
