# Generated by Django 5.2.17 on 2026-09-19 20:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.CharField(max_length=120)),
                ('event_id', models.UUIDField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer', 'event_id'), name='uniq_inbox_consumer_event')],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('legal_basis_ref', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('retired', 'Desativada')], default='draft', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_policies', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('display_name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('internal', 'Interno administrativo'), ('personal', 'Pessoal restrito'), ('financial', 'Financeiro restrito'), ('legal', 'Jurídico sigiloso')], max_length=16)),
                ('status', models.CharField(choices=[('quarantined', 'Em quarentena'), ('available', 'Disponível'), ('rejected', 'Rejeitado'), ('archived', 'Arquivado')], default='quarantined', max_length=16)),
                ('legal_hold', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('retention_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.retentionpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('minimized_diff', models.JSONField(blank=True, default=dict)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['campaign', 'occurred_at'], name='core_audite_campaig_f1fc0f_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_audite_resourc_b04f3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('media_type', models.CharField(max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('scan_status', models.CharField(choices=[('pending', 'Pendente'), ('clean', 'Aprovado'), ('rejected', 'Rejeitado'), ('error', 'Erro')], default='pending', max_length=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_scope', models.CharField(max_length=160)),
                ('route', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('result_ref', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'actor_scope', 'route', 'key_hash'), name='uniq_idempotency_scope_route_key')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=120)),
                ('aggregate_type', models.CharField(max_length=120)),
                ('aggregate_id', models.CharField(max_length=120)),
                ('aggregate_version', models.PositiveBigIntegerField(default=1)),
                ('payload_minimized', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('published', 'Publicado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=16)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=120)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.campaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='core_outbox_status_68cde3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_retention_policy_tenant_code'),
        ),
    ]
