# Generated by Django 5.2.17 on 2026-09-19 20:52

import apps.forms.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('published', 'Publicado'), ('paused', 'Pausado'), ('closed', 'Encerrado'), ('archived', 'Arquivado')], default='draft', max_length=16)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('schema_json', models.JSONField()),
                ('schema_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovada'), ('published', 'Publicada'), ('retired', 'Desativada')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_form_versions', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='forms.form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forms.formversion'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('display_name_ciphertext', models.BinaryField()),
                ('review_status', models.CharField(choices=[('pending', 'Pendente'), ('in_review', 'Em revisão'), ('released', 'Liberado'), ('restricted', 'Restrito')], default='pending', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retention_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.retentionpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('email', 'E-mail'), ('phone', 'Telefone')], max_length=16)),
                ('value_ciphertext', models.BinaryField()),
                ('match_hmac', models.CharField(db_index=True, max_length=64)),
                ('verification_state', models.CharField(choices=[('unverified', 'Não verificado'), ('challenge_sent', 'Desafio enviado'), ('verified', 'Verificado'), ('expired', 'Expirado')], default='unverified', max_length=24)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_points', to='forms.person')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyNoticeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovado'), ('retired', 'Desativado')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_privacy_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='formversion',
            name='notice_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.privacynoticeversion'),
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('protocol', models.CharField(default=apps.forms.models.opaque_code, max_length=80, unique=True)),
                ('request_type', models.CharField(choices=[('access', 'Acesso'), ('correction', 'Correção'), ('suppression', 'Supressão'), ('deletion', 'Eliminação')], max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(default='pending', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('decision_ref', models.CharField(blank=True, max_length=180)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField()),
                ('legal_basis_ref', models.CharField(max_length=255)),
                ('allowed_fields', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativa'), ('retired', 'Desativada')], default='draft', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retention_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.retentionpolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='privacynoticeversion',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notice_versions', to='forms.processingpurpose'),
        ),
        migrations.AddField(
            model_name='form',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='forms.processingpurpose'),
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('public_code', models.CharField(default=apps.forms.models.opaque_code, max_length=80, unique=True)),
                ('source_type', models.CharField(default='direct', max_length=80)),
                ('source_ref', models.CharField(blank=True, max_length=160)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='forms.form')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('capture_mode', models.CharField(choices=[('direct', 'Direto'), ('assisted', 'Assistido')], max_length=16)),
                ('payload_ciphertext', models.BinaryField()),
                ('processing_status', models.CharField(choices=[('received', 'Recebida'), ('processing', 'Em processamento'), ('processed', 'Processada'), ('rejected', 'Rejeitada'), ('review_required', 'Revisão necessária')], db_index=True, default='received', max_length=24)),
                ('assisted_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formversion')),
                ('source_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.sourcelink')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('protocol', models.CharField(default=apps.forms.models.opaque_code, max_length=80, unique=True)),
                ('category', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('received', 'Recebida'), ('triage', 'Em triagem'), ('in_progress', 'Em atendimento'), ('waiting_person', 'Aguardando pessoa'), ('resolved', 'Resolvida'), ('closed', 'Encerrada')], default='received', max_length=24)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('choice', models.CharField(choices=[('granted', 'Concedida'), ('denied', 'Negada'), ('revoked', 'Revogada')], max_length=16)),
                ('method', models.CharField(max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.person')),
                ('notice_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.privacynoticeversion')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.processingpurpose')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='forms.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.CharField(default=apps.forms.models.opaque_code, max_length=80, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='forms.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('contact_hmac', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(max_length=255)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_request_id', models.CharField(blank=True, max_length=120)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.processingpurpose')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('purpose_scope', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.contactpoint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contactpoint',
            index=models.Index(fields=['person', 'type', 'match_hmac'], name='forms_conta_person__c05f55_idx'),
        ),
        migrations.AddConstraint(
            model_name='formversion',
            constraint=models.UniqueConstraint(fields=('form', 'version_number'), name='uniq_form_version_number'),
        ),
        migrations.AddConstraint(
            model_name='processingpurpose',
            constraint=models.UniqueConstraint(fields=('campaign', 'code'), name='uniq_purpose_campaign_code'),
        ),
        migrations.AddConstraint(
            model_name='privacynoticeversion',
            constraint=models.UniqueConstraint(fields=('purpose', 'version'), name='uniq_notice_purpose_version'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('campaign', 'slug'), name='uniq_form_campaign_slug'),
        ),
        migrations.AddConstraint(
            model_name='suppression',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact_hmac', 'purpose'), name='uniq_suppression_campaign_contact_purpose'),
        ),
    ]
