# Generated by Django 5.2.17 on 2026-09-20 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_seed_operations_permissions'),
        ('forms', '0003_formversion_created_by'),
        ('workspace', '0002_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=160, verbose_name='Comitê / ponto de apoio')),
                ('base_type', models.CharField(choices=[('committee', 'Comitê eleitoral'), ('support', 'Ponto de apoio'), ('event', 'Local de evento público'), ('logistics', 'Base de logística')], default='committee', max_length=20, verbose_name='Tipo')),
                ('public_address', models.CharField(max_length=250, verbose_name='Endereço público do local')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('opening_hours', models.CharField(blank=True, max_length=160, verbose_name='Horário de funcionamento')),
                ('accessible', models.BooleanField(default=False, verbose_name='Acessibilidade conferida')),
                ('public_location_confirmed', models.BooleanField(default=False, verbose_name='Confirmo que é um local de operação, não residência de eleitor')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectorRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('municipality', models.CharField(blank=True, max_length=120, verbose_name='Município informado')),
                ('source', models.CharField(choices=[('voluntary', 'Cadastro voluntário'), ('assisted', 'Cadastro assistido')], max_length=16, verbose_name='Origem')),
                ('status', models.CharField(choices=[('pending', 'Aguardando revisão'), ('registered', 'Cadastro conferido'), ('suppressed', 'Contato suprimido')], default='pending', max_length=20)),
                ('evidence_reference', models.CharField(max_length=180, verbose_name='Referência da manifestação / solicitação')),
                ('consent_verified_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='elector_registration', to='forms.person')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.processingpurpose')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120, verbose_name='Nome do território')),
                ('municipality', models.CharField(max_length=120, verbose_name='Município')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge_code', models.CharField(blank=True, max_length=7, verbose_name='Código IBGE (opcional)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição da área de operação')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=150, verbose_name='Nome do integrante')),
                ('function', models.CharField(choices=[('coordinator', 'Coordenador(a) territorial'), ('field_organizer', 'Cabo eleitoral'), ('volunteer', 'Voluntário(a)'), ('event_staff', 'Equipe de eventos'), ('poll_observer', 'Fiscal / apoio eleitoral'), ('logistics', 'Apoio logístico')], default='volunteer', max_length=24, verbose_name='Função na campanha')),
                ('availability', models.CharField(blank=True, max_length=180, verbose_name='Disponibilidade declarada')),
                ('onboarding_reference', models.CharField(max_length=180, verbose_name='Referência do termo de participação')),
                ('training_status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída')], default='pending', max_length=16, verbose_name='Capacitação')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('ended', 'Desligado')], default='active', max_length=16)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workspace.campaignbase')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_profiles', to='campaigns.membership')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('approved', 'Aprovado'), ('active', 'Em execução'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('activity_type', models.CharField(choices=[('public_event', 'Ato / encontro público'), ('street_team', 'Equipe de rua'), ('materials', 'Distribuição geral de material'), ('committee_shift', 'Plantão de comitê'), ('training', 'Formação de equipe'), ('logistics', 'Operação logística'), ('accessibility', 'Apoio de acessibilidade')], max_length=24, verbose_name='Tipo de ação')),
                ('starts_at', models.DateTimeField(verbose_name='Início')),
                ('ends_at', models.DateTimeField(verbose_name='Fim')),
                ('required_staff', models.PositiveIntegerField(default=1, verbose_name='Pessoas necessárias')),
                ('operational_checklist', models.TextField(verbose_name='Checklist operacional')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.campaignbase')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.territory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaignbase',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.territory'),
        ),
        migrations.CreateModel(
            name='CampaignProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('candidate_name', models.CharField(max_length=150, verbose_name='Nome público da candidatura')),
                ('ballot_number', models.CharField(blank=True, max_length=5, verbose_name='Número da candidatura')),
                ('party', models.CharField(blank=True, max_length=120, verbose_name='Partido / federação')),
                ('office', models.CharField(choices=[('vereador', 'Vereador(a)'), ('prefeito', 'Prefeito(a)'), ('deputado_estadual', 'Deputado(a) estadual'), ('deputado_federal', 'Deputado(a) federal'), ('senador', 'Senador(a)'), ('governador', 'Governador(a)'), ('presidente', 'Presidente'), ('a_definir', 'A definir')], default='a_definir', max_length=40, verbose_name='Cargo')),
                ('election_date', models.DateField(blank=True, null=True, verbose_name='Data da eleição (confirmada pela equipe)')),
                ('campaign_region', models.CharField(max_length=180, verbose_name='Abrangência da campanha')),
                ('motto', models.CharField(blank=True, max_length=180, verbose_name='Identificação / lema público')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign',), name='uniq_campaign_public_profile')],
            },
        ),
        migrations.CreateModel(
            name='FieldAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('role_description', models.CharField(max_length=180, verbose_name='Responsabilidade na ação')),
                ('status', models.CharField(choices=[('scheduled', 'Escalado'), ('confirmed', 'Confirmado'), ('checked_in', 'Presença registrada'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=16)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workspace.fieldactivity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workspace.fieldworker')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activity', 'worker'), name='uniq_field_assignment')],
            },
        ),
    ]
