# Generated by Django 5.2.17 on 2026-09-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_legalcaseaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='area_kind',
            field=models.CharField(choices=[('operation', 'Território operacional'), ('district', 'Distrito'), ('neighborhood', 'Bairro'), ('community', 'Comunidade')], default='operation', max_length=20),
        ),
        migrations.AddField(
            model_name='territory',
            name='boundary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='territory',
            name='public_area_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='territory',
            name='source_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
