# Generated by Django 5.2.17 on 2026-09-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0008_territory_area_kind_territory_boundary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electorregistration",
            name="first_vote",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Primeira vez votando"
            ),
        ),
        migrations.AddField(
            model_name="electorregistration",
            name="voter_title_ciphertext",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaignbase",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="campaignbase",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
