# Generated by Django 5.2.17 on 2026-09-19 21:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_seed_operations_permissions'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('justification', models.TextField()),
                ('destination', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviada'), ('quoting', 'Em cotação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('cancelled', 'Cancelada')], default='draft', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=32)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=32)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='operations.purchaserequest')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('blocked', 'Bloqueado'), ('archived', 'Arquivado')], default='active', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Em elaboração'), ('approved', 'Aprovado'), ('active', 'Vigente'), ('partially_received', 'Parcialmente recebido'), ('received', 'Recebido'), ('closed', 'Encerrado')], default='draft', max_length=24)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='operations.purchaserequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Crítica')], default='normal', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execução'), ('blocked', 'Bloqueada'), ('in_review', 'Em revisão'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='open', max_length=16)),
                ('completion_criteria', models.TextField(blank=True)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='campaigns.membership')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='operations.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_tasks', to='operations.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='operations.task')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('code', models.SlugField(max_length=80)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('return', 'Devolução')], max_length=16)),
                ('signed_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('reason', models.CharField(max_length=500)),
                ('origin_type', models.CharField(blank=True, max_length=80)),
                ('origin_id', models.UUIDField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='operations.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='campaigns.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='operations.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physical_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='operations.stockitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='operations.warehouse')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['campaign', 'status', 'created_at'], name='operations__campaig_097a5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'sku'), name='uniq_stock_item_campaign_sku'),
        ),
        migrations.AddConstraint(
            model_name='purchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='purchase_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='uniq_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on')), _negated=True), name='task_cannot_depend_on_itself'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('campaign', 'code'), name='uniq_warehouse_campaign_code'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['campaign', 'item', 'warehouse', 'created_at'], name='operations__campaig_066519_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('signed_quantity', 0), _negated=True), name='stock_movement_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='uniq_stock_balance_item_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('physical_quantity__gte', 0)), name='stock_physical_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('physical_quantity'))), name='stock_reserved_not_above_physical'),
        ),
    ]
